# Generated by Django 5.0.3 on 2024-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='token_login',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.DeleteModel(
            name='UserSite',
        ),
    ]
