# Generated by Django 5.0.3 on 2024-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0002_buycar_token_login_delete_usersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='site',
            field=models.CharField(choices=[('S', 'Saipa'), ('D', 'Dizel')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
