# Generated by Django 5.0.3 on 2024-03-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0003_buycar_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('site', models.CharField(choices=[('S', 'Saipa'), ('D', 'Dizel')], max_length=1)),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buycar',
            name='site',
        ),
        migrations.AlterField(
            model_name='buycar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_car.car'),
        ),
    ]
