# Generated by Django 5.0.3 on 2024-03-05 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0004_car_remove_buycar_site_alter_buycar_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycar',
            name='cart_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
