# Generated by Django 5.0.3 on 2024-03-05 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0006_alter_buycar_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('text_captcha', models.CharField(blank=True, max_length=127, null=True)),
                ('buy_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_car.buycar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBuyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('date', models.DateTimeField()),
                ('max_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
