# Generated by Django 5.0.3 on 2024-03-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0007_captcha_historybuycar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='image',
            field=models.ImageField(upload_to='captcha/images'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='text_captcha',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
