# Generated by Django 5.0.3 on 2024-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_car', '0008_alter_captcha_image_alter_captcha_text_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captcha/images'),
        ),
    ]
