# Generated by Django 5.0.3 on 2024-03-09 15:35

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_site',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username_site',
            field=models.CharField(default=21, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='National Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
